import { Restaurant, MenuItem } from './storage';

export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Spice Villa',
    cuisine: ['North Indian', 'Mughlai'],
    rating: 4.5,
    deliveryTime: '30-35 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '2',
    name: 'South Delight',
    cuisine: ['South Indian', 'Kerala'],
    rating: 4.7,
    deliveryTime: '25-30 min',
    priceRange: '₹',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800&h=600&fit=crop',
    isVeg: true,
  },
  {
    id: '3',
    name: 'Punjab Dhaba',
    cuisine: ['North Indian', 'Punjabi'],
    rating: 4.6,
    deliveryTime: '35-40 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '4',
    name: 'Mumbai Chaat',
    cuisine: ['Street Food', 'Chaat'],
    rating: 4.3,
    deliveryTime: '20-25 min',
    priceRange: '₹',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&h=600&fit=crop',
    isVeg: true,
  },
  {
    id: '5',
    name: 'Sweet Heaven',
    cuisine: ['Desserts', 'Mithai'],
    rating: 4.8,
    deliveryTime: '25-30 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=600&fit=crop',
    isVeg: true,
  },
  {
    id: '6',
    name: 'Biryani House',
    cuisine: ['North Indian', 'Biryani'],
    rating: 4.6,
    deliveryTime: '30-35 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '7',
    name: 'Tandoor Junction',
    cuisine: ['North Indian', 'Tandoori'],
    rating: 4.4,
    deliveryTime: '30-35 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '8',
    name: 'Snack Corner',
    cuisine: ['Snacks', 'Fast Food'],
    rating: 4.2,
    deliveryTime: '20-25 min',
    priceRange: '₹',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=600&fit=crop',
    isVeg: true,
  },
  {
    id: '9',
    name: 'Bengali Rasoi',
    cuisine: ['Bengali', 'East Indian'],
    rating: 4.5,
    deliveryTime: '35-40 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '10',
    name: 'Rajasthani Thali',
    cuisine: ['Rajasthani', 'Thali'],
    rating: 4.7,
    deliveryTime: '40-45 min',
    priceRange: '₹₹₹',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop',
    isVeg: true,
  },
  {
    id: '11',
    name: 'Coastal Curry',
    cuisine: ['South Indian', 'Coastal'],
    rating: 4.6,
    deliveryTime: '30-35 min',
    priceRange: '₹₹',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&h=600&fit=crop',
    isVeg: false,
  },
  {
    id: '12',
    name: 'Paratha Point',
    cuisine: ['North Indian', 'Breakfast'],
    rating: 4.4,
    deliveryTime: '25-30 min',
    priceRange: '₹',
    image: 'https://images.unsplash.com/photo-1683533761804-5fc12be0f684?auto=format&fit=crop&w=1920&q=80&ixlib=rb-4.1.0',
    isVeg: true,
  },
];

export const mockMenuItems: MenuItem[] = [
  // Spice Villa (Restaurant 1)
  {
    id: 'm1',
    restaurantId: '1',
    name: 'Butter Chicken',
    description: 'Tender chicken in rich tomato gravy',
    price: 320,
    category: 'Main Course',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=300&fit=crop',
  },
  {
    id: 'm2',
    restaurantId: '1',
    name: 'Paneer Tikka Masala',
    description: 'Grilled cottage cheese in spicy gravy',
    price: 280,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm3',
    restaurantId: '1',
    name: 'Dal Makhani',
    description: 'Creamy black lentils slow-cooked',
    price: 220,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm4',
    restaurantId: '1',
    name: 'Garlic Naan',
    description: 'Soft bread with garlic butter',
    price: 60,
    category: 'Breads',
    isVeg: true,
  },
  {
    id: 'm5',
    restaurantId: '1',
    name: 'Chicken Seekh Kebab',
    description: 'Minced chicken skewers with spices',
    price: 280,
    category: 'Starters',
    isVeg: false,
  },
  {
    id: 'm6',
    restaurantId: '1',
    name: 'Malai Kofta',
    description: 'Cottage cheese dumplings in creamy gravy',
    price: 260,
    category: 'Main Course',
    isVeg: true,
  },
  
  // South Delight (Restaurant 2)
  {
    id: 'm7',
    restaurantId: '2',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe with spiced potato filling',
    price: 120,
    category: 'Main Course',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop',
  },
  {
    id: 'm8',
    restaurantId: '2',
    name: 'Idli Sambhar',
    description: 'Steamed rice cakes with lentil soup',
    price: 80,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm9',
    restaurantId: '2',
    name: 'Kerala Fish Curry',
    description: 'Fish in coconut-based tangy gravy',
    price: 340,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm10',
    restaurantId: '2',
    name: 'Medu Vada',
    description: 'Crispy lentil fritters',
    price: 90,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm11',
    restaurantId: '2',
    name: 'Uttapam',
    description: 'Thick rice pancake with vegetables',
    price: 130,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm12',
    restaurantId: '2',
    name: 'Filter Coffee',
    description: 'Traditional South Indian coffee',
    price: 50,
    category: 'Beverages',
    isVeg: true,
  },

  // Punjab Dhaba (Restaurant 3)
  {
    id: 'm13',
    restaurantId: '3',
    name: 'Chole Bhature',
    description: 'Spicy chickpeas with fried bread',
    price: 140,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm14',
    restaurantId: '3',
    name: 'Amritsari Kulcha',
    description: 'Stuffed bread with potato filling',
    price: 110,
    category: 'Breads',
    isVeg: true,
  },
  {
    id: 'm15',
    restaurantId: '3',
    name: 'Tandoori Chicken',
    description: 'Clay oven grilled chicken with spices',
    price: 380,
    category: 'Main Course',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop',
  },
  {
    id: 'm16',
    restaurantId: '3',
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese in butter tomato gravy',
    price: 270,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm17',
    restaurantId: '3',
    name: 'Lassi',
    description: 'Thick yogurt drink',
    price: 70,
    category: 'Beverages',
    isVeg: true,
  },
  {
    id: 'm18',
    restaurantId: '3',
    name: 'Sarson Ka Saag',
    description: 'Mustard greens curry with makki roti',
    price: 240,
    category: 'Main Course',
    isVeg: true,
  },

  // Mumbai Chaat (Restaurant 4)
  {
    id: 'm19',
    restaurantId: '4',
    name: 'Pani Puri',
    description: 'Crispy shells with tangy water',
    price: 60,
    category: 'Chaat',
    isVeg: true,
  },
  {
    id: 'm20',
    restaurantId: '4',
    name: 'Bhel Puri',
    description: 'Puffed rice with chutneys',
    price: 70,
    category: 'Chaat',
    isVeg: true,
  },
  {
    id: 'm21',
    restaurantId: '4',
    name: 'Sev Puri',
    description: 'Crispy base with potato and chutneys',
    price: 80,
    category: 'Chaat',
    isVeg: true,
  },
  {
    id: 'm22',
    restaurantId: '4',
    name: 'Dahi Puri',
    description: 'Crispy shells with yogurt and chutney',
    price: 90,
    category: 'Chaat',
    isVeg: true,
  },
  {
    id: 'm23',
    restaurantId: '4',
    name: 'Ragda Pattice',
    description: 'Potato patties with white pea curry',
    price: 100,
    category: 'Chaat',
    isVeg: true,
  },
  {
    id: 'm24',
    restaurantId: '4',
    name: 'Papdi Chaat',
    description: 'Crispy wafers with yogurt and chutneys',
    price: 85,
    category: 'Chaat',
    isVeg: true,
  },

  // Sweet Heaven (Restaurant 5)
  {
    id: 'm25',
    restaurantId: '5',
    name: 'Gulab Jamun',
    description: 'Soft milk dumplings in sugar syrup',
    price: 80,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm26',
    restaurantId: '5',
    name: 'Jalebi',
    description: 'Crispy sugar spirals',
    price: 90,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm27',
    restaurantId: '5',
    name: 'Ras Malai',
    description: 'Cottage cheese in sweetened milk',
    price: 100,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm28',
    restaurantId: '5',
    name: 'Gajar Halwa',
    description: 'Carrot pudding with nuts',
    price: 110,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm29',
    restaurantId: '5',
    name: 'Kulfi Falooda',
    description: 'Traditional ice cream with vermicelli',
    price: 120,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm30',
    restaurantId: '5',
    name: 'Kaju Katli',
    description: 'Cashew fudge sweet',
    price: 150,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm31',
    restaurantId: '5',
    name: 'Rasgulla',
    description: 'Soft cottage cheese balls in syrup',
    price: 85,
    category: 'Desserts',
    isVeg: true,
  },

  // Biryani House (Restaurant 6)
  {
    id: 'm32',
    restaurantId: '6',
    name: 'Hyderabadi Biryani',
    description: 'Aromatic rice with tender chicken',
    price: 350,
    category: 'Main Course',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
  },
  {
    id: 'm33',
    restaurantId: '6',
    name: 'Veg Biryani',
    description: 'Fragrant rice with mixed vegetables',
    price: 280,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm34',
    restaurantId: '6',
    name: 'Mutton Biryani',
    description: 'Spiced rice with tender mutton',
    price: 420,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm35',
    restaurantId: '6',
    name: 'Raita',
    description: 'Yogurt with cucumber and spices',
    price: 60,
    category: 'Sides',
    isVeg: true,
  },
  {
    id: 'm36',
    restaurantId: '6',
    name: 'Mirchi Ka Salan',
    description: 'Spicy chili curry',
    price: 140,
    category: 'Sides',
    isVeg: true,
  },
  {
    id: 'm37',
    restaurantId: '6',
    name: 'Double Ka Meetha',
    description: 'Bread pudding dessert',
    price: 100,
    category: 'Desserts',
    isVeg: true,
  },

  // Tandoor Junction (Restaurant 7)
  {
    id: 'm38',
    restaurantId: '7',
    name: 'Tandoori Paneer Tikka',
    description: 'Grilled cottage cheese marinated in spices',
    price: 290,
    category: 'Starters',
    isVeg: true,
  },
  {
    id: 'm39',
    restaurantId: '7',
    name: 'Chicken Tikka',
    description: 'Boneless chicken grilled in tandoor',
    price: 320,
    category: 'Starters',
    isVeg: false,
  },
  {
    id: 'm40',
    restaurantId: '7',
    name: 'Tandoori Roti',
    description: 'Whole wheat bread from clay oven',
    price: 40,
    category: 'Breads',
    isVeg: true,
  },
  {
    id: 'm41',
    restaurantId: '7',
    name: 'Afghani Chicken',
    description: 'Creamy chicken with cashew paste',
    price: 360,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm42',
    restaurantId: '7',
    name: 'Mushroom Tikka',
    description: 'Grilled mushrooms with spices',
    price: 260,
    category: 'Starters',
    isVeg: true,
  },
  {
    id: 'm43',
    restaurantId: '7',
    name: 'Seekh Paratha',
    description: 'Kebab wrapped in paratha',
    price: 200,
    category: 'Breads',
    isVeg: false,
  },

  // Snack Corner (Restaurant 8)
  {
    id: 'm44',
    restaurantId: '8',
    name: 'Samosa',
    description: 'Crispy pastry with spiced potato',
    price: 40,
    category: 'Snacks',
    isVeg: true,
  },
  {
    id: 'm45',
    restaurantId: '8',
    name: 'Pav Bhaji',
    description: 'Spiced vegetable curry with bread',
    price: 100,
    category: 'Snacks',
    isVeg: true,
  },
  {
    id: 'm46',
    restaurantId: '8',
    name: 'Vada Pav',
    description: 'Spicy potato fritter in bread bun',
    price: 50,
    category: 'Snacks',
    isVeg: true,
  },
  {
    id: 'm47',
    restaurantId: '8',
    name: 'Dabeli',
    description: 'Spiced potato mixture in pav',
    price: 60,
    category: 'Snacks',
    isVeg: true,
  },
  {
    id: 'm48',
    restaurantId: '8',
    name: 'Aloo Tikki',
    description: 'Potato cutlet with chutneys',
    price: 70,
    category: 'Snacks',
    isVeg: true,
  },
  {
    id: 'm49',
    restaurantId: '8',
    name: 'Kachori',
    description: 'Fried pastry with lentil filling',
    price: 45,
    category: 'Snacks',
    isVeg: true,
  },

  // Bengali Rasoi (Restaurant 9)
  {
    id: 'm50',
    restaurantId: '9',
    name: 'Machher Jhol',
    description: 'Bengali fish curry with vegetables',
    price: 340,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm51',
    restaurantId: '9',
    name: 'Kosha Mangsho',
    description: 'Slow-cooked mutton curry',
    price: 420,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm52',
    restaurantId: '9',
    name: 'Shukto',
    description: 'Mixed vegetable with bitter gourd',
    price: 220,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm53',
    restaurantId: '9',
    name: 'Mishti Doi',
    description: 'Sweet yogurt dessert',
    price: 80,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm54',
    restaurantId: '9',
    name: 'Sandesh',
    description: 'Cottage cheese sweet',
    price: 90,
    category: 'Desserts',
    isVeg: true,
  },
  {
    id: 'm55',
    restaurantId: '9',
    name: 'Luchi Alur Dom',
    description: 'Fried bread with spiced potato curry',
    price: 150,
    category: 'Main Course',
    isVeg: true,
  },

  // Rajasthani Thali (Restaurant 10)
  {
    id: 'm56',
    restaurantId: '10',
    name: 'Rajasthani Thali',
    description: 'Complete meal with dal, vegetables, roti, rice',
    price: 450,
    category: 'Thali',
    isVeg: true,
  },
  {
    id: 'm57',
    restaurantId: '10',
    name: 'Dal Baati Churma',
    description: 'Lentils with baked wheat balls and sweet',
    price: 320,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm58',
    restaurantId: '10',
    name: 'Gatte Ki Sabzi',
    description: 'Gram flour dumplings in yogurt curry',
    price: 240,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm59',
    restaurantId: '10',
    name: 'Ker Sangri',
    description: 'Desert beans and berries curry',
    price: 260,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm60',
    restaurantId: '10',
    name: 'Laal Maas',
    description: 'Spicy red mutton curry',
    price: 440,
    category: 'Main Course',
    isVeg: false,
  },

  // Coastal Curry (Restaurant 11)
  {
    id: 'm61',
    restaurantId: '11',
    name: 'Goan Fish Curry',
    description: 'Fish in coconut and tamarind gravy',
    price: 360,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm62',
    restaurantId: '11',
    name: 'Prawn Balchao',
    description: 'Spicy prawn pickle-style curry',
    price: 400,
    category: 'Main Course',
    isVeg: false,
  },
  {
    id: 'm63',
    restaurantId: '11',
    name: 'Sol Kadhi',
    description: 'Coconut milk and kokum drink',
    price: 60,
    category: 'Beverages',
    isVeg: true,
  },
  {
    id: 'm64',
    restaurantId: '11',
    name: 'Appam with Stew',
    description: 'Rice pancakes with vegetable stew',
    price: 180,
    category: 'Main Course',
    isVeg: true,
  },
  {
    id: 'm65',
    restaurantId: '11',
    name: 'Karimeen Pollichathu',
    description: 'Pearl spot fish grilled in banana leaf',
    price: 420,
    category: 'Main Course',
    isVeg: false,
  },

  // Paratha Point (Restaurant 12)
  {
    id: 'm66',
    restaurantId: '12',
    name: 'Aloo Paratha',
    description: 'Potato stuffed flatbread',
    price: 90,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm67',
    restaurantId: '12',
    name: 'Paneer Paratha',
    description: 'Cottage cheese stuffed flatbread',
    price: 110,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm68',
    restaurantId: '12',
    name: 'Gobi Paratha',
    description: 'Cauliflower stuffed flatbread',
    price: 100,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm69',
    restaurantId: '12',
    name: 'Mix Veg Paratha',
    description: 'Mixed vegetable stuffed flatbread',
    price: 120,
    category: 'Breakfast',
    isVeg: true,
  },
  {
    id: 'm70',
    restaurantId: '12',
    name: 'Curd',
    description: 'Fresh yogurt',
    price: 40,
    category: 'Sides',
    isVeg: true,
  },
  {
    id: 'm71',
    restaurantId: '12',
    name: 'Pickle',
    description: 'Assorted Indian pickles',
    price: 30,
    category: 'Sides',
    isVeg: true,
  },
];

export const categories = [
  { id: 'north-indian', name: 'North Indian', icon: '🍛' },
  { id: 'south-indian', name: 'South Indian', icon: '🥘' },
  { id: 'punjabi', name: 'Punjabi', icon: '🫓' },
  { id: 'street-food', name: 'Street Food', icon: '🍟' },
  { id: 'desserts', name: 'Desserts', icon: '🍰' },
  { id: 'biryani', name: 'Biryani', icon: '🍚' },
];
